### ISSUE TITLE
Footer area is empty

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#1]
Add content to the footer area!

**Comment by Suldana** [comment]
Hi @duraanali can you assign this to me

**Comment by duraanali** [comment]
@Suldana , Yes!

**Comment by Suldana** [comment]
Hey @duraanali i'm not able to locate the footer, can you please help me??

**Comment by Suldana** [comment]
Hi @duraanali 

![Screenshot 2023-07-31 140828](https://github.com/duraanali/luuqad/assets/114906181/65acd43b-963e-4cd7-aae3-9ce81195807d)

We designed to the figma file, but I am unable to find the resources and materials for this project. If you know where I can look for it, please let me know. as well as designed the footer for this landing page, check to see if it is acceptable to turn it into code, Thanks 

![image](https://github.com/duraanali/luuqad/assets/114906181/f70c8c88-c771-480a-844b-2466a497d257)
