### ISSUE TITLE
Add a language icon on the landing page 

### ISSUE THREAD

**Issue by Iqra-Issack** [duraanali/luuqad#10]
Since we are doing translation ,We need to have the option of English and Somali language for people to choose which language they want to learn with.

![duolingo landind page ](https://github.com/duraanali/luuqad/assets/140454697/9b1f55e2-3507-427e-9982-00f1e903a62f)

**Comment by duraanali** [comment]
I added another issue where will use NextJS internationalization system, I added more info there, I will close this issue for now.
