### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Engr-Pirlo** [duraanali/luuqad#106]
### Description

Asc Engr duran, Waxan arkay Xogaho Iney Cilad ka jirta dhanka Code iyo Fahankiisa Marka waxan Fiican inan, Loo Sameyo Comments Every Line Code iyo Every file oo Code Ku Qoran that's My Issue

### Suggested Solution

Waxan Fiican Inan Sameyeyno Commentigas Si ay Developerska kale u fahaman code, Madama Project uu Yahay Project Ay dad badan ka shaqeynayaa Waa Muhiim code in La fahmo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by duraanali** [comment]
Waan jeclaan lahaa inaan comment galino code-ka lakin aad ayuu u badanyahay, qayb hadaa su'aal ka qabto waan isku dayi inaan ka jawaabo.

**Comment by Engr-Pirlo** [comment]
Dhibmalahan Engr aniga Qeybtas So Sa Sameyno Insha allah, dhaaman files aniga ku sodaraayo inshallah
