### ISSUE TITLE
Data Entry: We need someone to enter Units, sections, questions and answers

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#116]
We already have an admin area where you can enter data, we want someone to enter data such as Units, Sections, questions and answers. Following the format we already have.

**Comment by duraanali** [comment]
@AbdirizakMohamedAbdilaahi Waan kugu assign gareeyay, Whatsapp igala soo xariir si aan kuu siiyo admin access aana kuugu faahfaahiyo.

**Comment by AbdirizakMohamedAbdilaahi** [comment]
@duraanali ustaadkeena diyaar weeye waana kaala soo xiriirey WhatsApp ka mahadsanid
