### ISSUE TITLE
Create the login form!

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#2]
The login page has a title and button, we want to add a login form and other buttons for google and facebook login. No need to do any functionality at this moment. Please follow the UI design attached. Use Tailwind CSS only. Thanks.

<img width="508" alt="loginform" src="https://github.com/duraanali/luuqad/assets/16447314/c09f39e9-76e5-42c4-909b-fa2c95827c39">

**Comment by IbnuAlii** [comment]
Assign me.

**Comment by munniomer** [comment]
@duraanali  assign this to @IbnuAlii

**Comment by Ashakour1** [comment]
i finished the login page check the pull request.

**Comment by duraanali** [comment]
Thanks @Ashakour1 !
