### ISSUE TITLE
Create the Forget Password Form.

### ISSUE THREAD

**Issue by munniomer** [duraanali/luuqad#29]
The Froget Password Form that is designed using Tailwind css , see the attached form duolingo website.

<img width="1248" alt="Screen Shot 2023-07-31 at 6 43 29 PM" src="https://github.com/duraanali/luuqad/assets/42119461/3c8d5596-b3e9-440a-8e77-02a909c442f9">

**Comment by Ashakour1** [comment]
assign me eng @duraanali
