### ISSUE TITLE
Align and space in Mobile view!! #3

### ISSUE THREAD

**Issue by Hodanbili** [duraanali/luuqad#3]
in mobile view  GET START button at top  of the page is better to align text (GET START) at center of button 
also increase space between LUUQAD text and button

![WhatsApp Image 2023-07-29 at 22 00 44](https://github.com/duraanali/luuqad/assets/117977777/258b2ade-cc13-4586-9675-68883481defc)
<img width="846" alt="Capture" src="https://github.com/duraanali/luuqad/assets/117977777/2bfc5b1a-cffa-4fa0-8360-fff719fb3907">

**Comment by duraanali** [comment]
Thanks for pointing it out, I will get to it :)

**Comment by munniomer** [comment]
@duraanali assign me this

**Comment by munniomer** [comment]
@duraanali I think this issue was fixed , should I close it?
