### ISSUE TITLE
Create lesson page with questions and answers (dummy data)

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#38]
We need someone to create a page when you click a certain lesson, We want each lesson to have questions and answers.

<img width="1433" alt="lesson22" src="https://github.com/duraanali/luuqad/assets/16447314/600756e7-54c5-4824-8515-2dca080a0dd3">
<img width="1440" alt="lesson444" src="https://github.com/duraanali/luuqad/assets/16447314/fcd6e14a-f921-4a91-a826-b38b7ab0b127">
<img width="1439" alt="lesson233" src="https://github.com/duraanali/luuqad/assets/16447314/b5aa3b76-41a0-47a3-b0b9-7913697cafb1">
<img width="1425" alt="lesson111" src="https://github.com/duraanali/luuqad/assets/16447314/a28aff1d-ac24-4e84-a439-b8762dfa6ca4">

**Comment by IbnuAlii** [comment]
assign to me @duraanali
