### ISSUE TITLE
The Link to the GitHub Discussion is broken

### ISSUE THREAD

**Issue by fatumahomar** [duraanali/luuqad#4]
The Link to the GitHub Discussion is broken.  It displays 404 error when clicked.

<img width="960" alt="error" src="https://github.com/duraanali/luuqad/assets/140343299/76e0adf4-2b94-4eb6-930c-1737cab7c397">

**Comment by fatumahomar** [comment]
Hi @duraanali , I tried adding the bug issue and good first issue label to this Issue , but I could not, Is it because am not a project maintainer. Can you please add Issue label to my Issue

**Comment by duraanali** [comment]
@fatumahomar, I'm not sure, I will look into that. Thanks for pointing this out!

**Comment by duraanali** [comment]
Thanks @fatumahomar, I fixed that link!

**Comment by fatumahomar** [comment]
No problem, happy to help
