### ISSUE TITLE
When logged in, hide "Get Started" at the top!

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#62]
When a user is logged in, we need to hide other parts of the website they're asked to login or signup.

**Comment by fatumahomar** [comment]
assign me

**Comment by duraanali** [comment]
import { authOptions } from '@/lib/auth'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import { Icons } from './Icons'
import { buttonVariants } from './ui/Button'
import { UserAccountNav } from './UserAccountNav'
import SearchBar from './SearchBar'

const Navbar = async () => {
  const session = await getServerSession(authOptions)
  return (
    <div className='fixed top-0 inset-x-0 h-fit bg-zinc-100 border-b border-zinc-300 z-[10] py-2'>
      <div className='container max-w-7xl h-full mx-auto flex items-center justify-between gap-2'>
        {/* logo */}
        <Link href='/' className='flex gap-2 items-center'>
          <Icons.logo className='h-8 w-8 sm:h-6 sm:w-6' />
          <p className='hidden text-zinc-700 text-sm font-medium md:block'>Breadit</p>
        </Link>

        {/* search bar */}
        <SearchBar />

        {/* actions */}
        {session?.user ? (
          <UserAccountNav user={session.user} />
        ) : (
          <Link href='/sign-in' className={buttonVariants()}>
            Sign In
          </Link>
        )}
      </div>
    </div>
  )
}

export default Navbar


You can use this as reference!

**Comment by duraanali** [comment]
@fatumahomar Asc, how is this task coming along?

**Comment by duraanali** [comment]
This task has changed since we changed the UI for the dashboard!
