### ISSUE TITLE
Design The curriculum for the first lesson!

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#66]
Use the style of Duolingo and design a lesson. Each Lesson contains Units and each Unit contains a quiz (the quiz has questions and answers).

We need someone to design basic English beginner lessons with written and sound organized in a way that can be used on the site.

You can use https://fliki.ai to get audio of English AND Somali.

**Comment by safacade009** [comment]
assign me to this

**Comment by duraanali** [comment]
Asc @safacade009 , intuu kuu maraayaa? Waxaan rabay inaan ogaado intaadan waqti badan ku bixin, ial soo socodsii.

**Comment by safacade009** [comment]
ustaad waxaa raadinaaye appication text iyo soundka halmar iskula xiri karo lkn hadaa soo push gareynaa i,a

**Comment by duraanali** [comment]
Thanks @safacade009
