### ISSUE TITLE
Add Rules to CONTRIBUTION 

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#72]
I want someone to add basic rules to the contribution file (Somali and English) of how we need the person working on new changes to first check issues, either create new issue or ask to be assigned to an issue.

Go to Whatsapp group for more information

**Comment by Suldana** [comment]
can you assign this to me @duraanali

**Comment by Hodanbili** [comment]
please assign me to do this

**Comment by mahamedmahad** [comment]
Is this Issue fixed or is there more to be added? @Hodanbili  has tagged in pr #79

**Comment by Ali-Ahmed-Mohammed** [comment]
Already approved

**Comment by Hodanbili** [comment]
I added new rules to new contributors issue #72

**Comment by duraanali** [comment]
I think we can close this!
