### ISSUE TITLE
[Feature]: Add Email sending feature

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#76]
### Description

We want someone to add a way to send notifications such as password reset and when someone first signs up. You can also create a couple of basic templates.

### Suggested Solution

You can use https://react.email/ with nodemailer plus sendgrid

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by yasinelabe** [comment]
@duraanali  assign me this , if no one is working on it

**Comment by duraanali** [comment]
Thanks @yasinelabe for completing the task! I will close it.
