### ISSUE TITLE
[Feature]: Create pages for the dashboard navigation and make it clickable!

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#77]
### Description

The navigation on the left side isn't doing anything, We want them to navigate to different pages. We also want the active link to have light blue background.

### Suggested Solution

Create nested components!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by ImSidow** [comment]
@duraanali  can please assign this to me
