### ISSUE TITLE
Alignment and Padding in Mobile View

### ISSUE THREAD

**Issue by Ali-Ahmed-Mohammed** [duraanali/luuqad#8]
After Getting  Started  **Sign Up**  and **Create Account**  button don`t  have suitable padding and not aligned text in the center { in mobile view }

![WhatsApp Image 2023-07-30 at 10 16 49](https://github.com/duraanali/luuqad/assets/134586233/17cf4850-a2d6-43c6-8907-1d436349ca63)
![WhatsApp Image 2023-07-30 at 10 16 50](https://github.com/duraanali/luuqad/assets/134586233/da7672c3-b25b-44f0-887c-c4941980afab)

**Comment by duraanali** [comment]
Thanks @Ali-Ahmed-Mohammed, We will fix mobile issues, thanks.

**Comment by duraanali** [comment]
This issue was fixed!
