### ISSUE TITLE
Video kusoo dar qaybta sida contribution loogu sameeyo!

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#80]
Waxaan sameeyay video gaaban oo yara sharaxaayo habka contribution loogu sameeyo project-ga. Video-ga oo embedded ah ama ka muuqanaayo documentation-ka soo gali.

Video: https://www.youtube.com/watch?v=1kymX200Mp8

**Comment by Iamgithublover252** [comment]
please assign to me

**Comment by duraanali** [comment]
Mahadsanid @Iamgithublover252
