### ISSUE TITLE
[BUG]   Incorrect Github Authentication Redirect to Localhost 

### ISSUE THREAD

**Issue by mahamedmahad** [duraanali/luuqad#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When attempting to log in using Github authentication on the luuqad.vercel.app website, the authentication process redirects to localhost instead of the correct GitHub login page when the local host (localhost) is active/inactive.  This issue does not occur when using the browser in private mode, but goes back to localhost after logged in. 

### Expected Behavior

After clicking the "Login with Github" button, the authentication process should take me to the correct Github login page. Once I log in, it should redirect me back to luuqad.vercel.app with a successful login.

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by duraanali** [comment]
Thanks for pointing it out, I will fix it!

**Comment by duraanali** [comment]
I fixed it, test it and let me know if it doesn't work for you! @mahamedmahad

**Comment by mahamedmahad** [comment]
It Works now 👍

**Comment by duraanali** [comment]
Good!
